# docker-compose.yml
version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  nginx:
    image: nginx:stable-alpine
    platform: linux/arm64
    ports:
      - "80:80"
    volumes:
      - ./laravel-app/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql/mysql-server:8.0
    platform: linux/arm64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: